### PR TITLE
Fix spacing error in vulcanized code.

### LINKED ISSUE #108: No space between "with" and Mixin name
See for example:

image

In theory this should be fixed by https://github.com/PolymerElements/iron-doc-viewer/commit/cf52573896b17c209c26109320fe8c4bf81152ad, but in practice it is not. I think either the HTML minification or some magic on the part of the `<template is="dom-repeat"` is removing the space. 

Adding a zero-width space before the template appears to prevent this problem.

`with &#8203;<template is="dom-repeat" ...>`

### PR DESCRIPTION
**Pull request by arthurevans**
Fixes #108 (I hope).

### CODE REVIEW

**Comment by arthurevans** [comment]
Ping @justinfagnani  @notwaldorf

**Comment by arthurevans** [comment]
Added one more change that separates the mixin list with commas, where they used to run together with no spaces.

You can see this issue currently here: https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.PropertyEffects

The core docs don't currently contain an element with multiple mixins listed. I verified the fix for iron-doc-element.html by adding a new fake mixin in devtools.

This should be up to date with the new branch. PTAL @aomarks

**Review by aomarks — APPROVED** [review]

**Comment by arthurevans** [comment]
Shall I go ahead and merge this?

**Comment by aomarks** [comment]
Yep go ahead.

**Pull request merged**
