### PR TITLE
Fix #183, add anchors for top-level exports.

### LINKED ISSUE #183: Top-level exports don't have anchors
I think this is just an issue that anchor-id is set as a property instead of an attribute on the sub-elements.

### PR DESCRIPTION
**Pull request by arthurevans**
The scroll is off a little on these anchors for some reason. But they seem to work.
If there's a better fix, please close this PR!

### CODE REVIEW

**Review by rictic — APPROVED** [review]
Nice!!

**Comment by arthurevans** [comment]
Thanks @rictic ... Two questions... Should I just merge this, or wait for approval from @aomarks?

And how do I go about getting this released? And should I bump the dependency version in the polymer docs repo? 

Oops! That's three questions!

**Comment by arthurevans** [comment]
Ping @rictic @aomarks ^^

**Review by aomarks — APPROVED** [review]

**Comment by aomarks** [comment]
> And how do I go about getting this released? And should I bump the dependency version in the polymer docs repo?

Edit bower.json with the new version, and then use the github "draft new release" button .

**Pull request merged**
