### PR TITLE
Convert over to hydrolysis' Analyzer.load interface.

### PR DESCRIPTION
**Pull request by nevir**

### CODE REVIEW

**Comment by nevir** [comment]
cc @mbleigh (next step is an element that wraps this interface)

**Comment by mbleigh** [comment]
Love how thin this makes `iron-doc-viewer`.

**Comment by nevir** [comment]
_hangs head in shame for test failures_

**Comment by nevir** [comment]
Oh blah, test failures are due to https://github.com/Polymer/polymer/pull/1407

**Pull request merged**
