### PR TITLE
fixes issue #23: cdn.rawgit.com-hosted files will never change after …

### PR DESCRIPTION
**Pull request by lucyllewy**
…first load

the code uses the github api to fetch the list of available tags and uses the first one in the list.
if there are no tags it will fall back to using the master branch.

### CODE REVIEW

**Comment by lucyllewy** [comment]
I signed it :-)

**Comment by lucyllewy** [comment]
ref: issue #23

**Comment by mbleigh** [comment]
This solution is somewhat problematic in that the GitHub API is **extremely rate-limited** for unauthenticated public requests. If someone were browsing a large number of elements they'd quickly hit the ceiling and things would start breaking.

I've been trying to come up with a solution to this myself, haven't landed on something I love yet other than hosting some kind of API proxy to get around the rate-limit issue.

**Comment by lucyllewy** [comment]
hmm, yes, I see there's a limit of 60 requests per hour per IP for unauthenticated requests. This can be read as 1 request per minute. Casual browsing might just get away with it. But more heavy use will fall afoul. I'm not sure what else we can do though.

(ref: https://developer.github.com/v3/#rate-limiting)

**Comment by cdata** [comment]
Thank you for your contribution! I'm going to close this PR for now, since it doesn't have a corresponding issue and / or corresponding tests. Please consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for help on filing issues and opening PRs in the future!

**Pull request closed without merging**
